"""Profile-specific requirements for the shared RTL unit verification runner."""

PROFILES = {
    'rename_bundle': dict(
        top='rename_bundle', sources=['rtl/backend/rename_bundle.sv'],
        inputs=[],
        headers=[], schema_checks=[], parameters={},
        timeout=180, random_key='random_cases_per_seed', prefix='RENAME BUNDLE PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: fields.get('seed') == seed and fields.get('cases') == 16264 + config['random_cases_per_seed'],
        required=['blocked', 'cut', 'raw', 'waw', 'zero'],
        negatives={}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='rename bundle mismatch', mutation_flags=[],
        mutations={
            'raw': ('rtl/backend/rename_bundle.sv', 'source1[1] = destination[0];', 'source1[1] = rat_i[rs1_i[5 +: 5]*6 +: 6];', 1),
            'waw': ('rtl/backend/rename_bundle.sv', 'stale[1] = destination[0];', 'stale[1] = rat_i[rd_i[5 +: 5]*6 +: 6];', 1),
            'duplicate_tag': ('rtl/backend/rename_bundle.sv', 'available[destination[lane]] = 0;', 'available[0] = 0;', 1),
            'partial_resources': ('rtl/backend/rename_bundle.sv', '&& resources_ready_i && enough', "&& resources_ready_i && (enough || valid_i != 2'b10)", 1),
            'branch_cut': ('rtl/backend/rename_bundle.sv', 'if (checkpoint_i[0]) selected[1] = 0;', 'if (checkpoint_i[0]) selected[1] = valid_i[1];', 1),
            'raw_ready': ('rtl/backend/rename_bundle.sv', 'operand_ready[1][0] = 0;', 'operand_ready[1][0] = ready_i[source1[1]];', 1),
        },
    ),
    'rename_state': dict(
        top='rename_state', sources=['rtl/backend/rename_bundle.sv', 'rtl/backend/rename_state.sv'],
        inputs=[],
        headers=[], schema_checks=[], parameters={},
        timeout=300, random_key='random_cycles_per_seed', prefix='RENAME STATE PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('cycles') != config['directed_cycles'] + config['random_cycles_per_seed']),
        required=['blocked_wb', 'checkpoint_cut', 'commit_rename', 'commit_waw', 'deferred_reuse', 'dual_rename', 'exhausted', 'ooo_wb', 'recover_collision', 'recovery', 'rename_waw', 'reset_live', 'tag_reuse', 'wb_bypass', 'wb_commit', 'wb_lane1', 'wb_zero', 'zero_destination'],
        negatives={'free_wb': (['negative', 'free_wb'], 'RENAME_STATE_WB_OWNER'), 'duplicate_wb': (['negative', 'duplicate_wb'], 'RENAME_STATE_DUPLICATE_WB'), 'unready_commit': (['negative', 'unready_commit'], 'RENAME_STATE_COMMIT_OWNER'), 'commit_prefix': (['negative', 'commit_prefix'], 'RENAME_STATE_COMMIT_PREFIX'), 'wrong_stale': (['negative', 'wrong_stale'], 'RENAME_STATE_COMMIT_OWNER'), 'zero_metadata': (['negative', 'zero_metadata'], 'RENAME_STATE_ZERO_COMMIT')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='rename state mismatch', mutation_flags=['-DSYNTHESIS'],
        mutations={
            'allocation_ready': ('rtl/backend/rename_state.sv', 'ready_d[destination_o[lane*6 +: 6]] = 0;', 'ready_d[destination_o[lane*6 +: 6]] = 1;', 1),
            'allocation_ownership': ('rtl/backend/rename_state.sv', 'free_d[destination_o[lane*6 +: 6]] = 0;', 'free_d[destination_o[lane*6 +: 6]] = 1;', 1),
            'wrong_release': ('rtl/backend/rename_state.sv', 'free_d[commit_stale_i[lane*6 +: 6]] = 1;', 'free_d[commit_destination_i[lane*6 +: 6]] = 1;', 1),
            'commit_lane_order': ('rtl/backend/rename_state.sv', 'committed_d[commit_rd_i[lane*5 +: 5]*6 +: 6] = commit_destination_i[lane*6 +: 6];', 'if (lane == 0) committed_d[commit_rd_i[lane*5 +: 5]*6 +: 6] = commit_destination_i[lane*6 +: 6];', 1),
            'recovery_map': ('rtl/backend/rename_state.sv', 'rat_d = committed_q;', 'rat_d = rat_q;', 1),
            'recovery_commit_leak': ('rtl/backend/rename_state.sv', 'committed_d = committed_q;\n      free_d = recovered_free;', 'committed_d = commit_i[0] ? rat_q : committed_q;\n      free_d = recovered_free;', 1),
            'wb_bypass': ('rtl/backend/rename_state.sv', '.ready_i(ready_view)', '.ready_i(ready_q)', 1),
            'retire_clobbers_speculative': ('rtl/backend/rename_state.sv', 'free_d[commit_stale_i[lane*6 +: 6]] = 1;', 'free_d[commit_stale_i[lane*6 +: 6]] = 1; rat_d = committed_d;', 1),
        },
    ),
    'rename_checkpoints': dict(
        top='rename_checkpoints', sources=['rtl/backend/rename_checkpoints.sv'],
        inputs=[],
        headers=[], schema_checks=[], parameters={},
        timeout=300, random_key='random_cycles_per_seed', prefix='RENAME CHECKPOINTS PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('cycles') != config['directed_cycles'] + config['random_cycles_per_seed']),
        required=['created', 'deferred_slot_reuse', 'flush_live', 'full_ordinary_rename', 'full_stall', 'link_retained', 'nested_recovery', 'older_commit', 'out_of_order_resolve', 'probes', 'recovery', 'recovery_collision', 'recycled_old_tag', 'reset_live', 'resolve_create', 'slot_reuse', 'suppressed_noise', 'two_lane_cfi', 'waw', 'younger_kill'],
        negatives={'invalid_resolve': (['negative', 'invalid_resolve'], 'CHECKPOINT_RESOLVE_LIVE'), 'zero_allocation': (['negative', 'zero_allocation'], 'CHECKPOINT_ALLOCATE_ZERO'), 'stalled_allocation': (['negative', 'stalled_allocation'], 'CHECKPOINT_STALLED_ALLOCATION'), 'duplicate_allocation': (['negative', 'duplicate_allocation'], 'CHECKPOINT_DUPLICATE_ALLOCATION'), 'map_zero': (['negative', 'map_zero'], 'CHECKPOINT_MAP_ZERO'), 'map_alias': (['negative', 'map_alias'], 'CHECKPOINT_MAP_ALIAS')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='rename checkpoints mismatch', mutation_flags=['-DSYNTHESIS'],
        mutations={
            'includes_cfi': ('rtl/backend/rename_checkpoints.sv', 'history_d[candidate] = 0;', 'history_d[candidate] = allocation_i;', 1),
            'lost_history': ('rtl/backend/rename_checkpoints.sv', 'history_q[slot] | allocation_i', 'history_q[slot] & allocation_i', 1),
            'wrong_snapshot': ('rtl/backend/rename_checkpoints.sv', 'snapshot_d[candidate] = snapshot_i;', "snapshot_d[candidate] = snapshot_i ^ 192'h40;", 1),
            'numeric_slot_age': ('rtl/backend/rename_checkpoints.sv', 'released_o = valid_q & ~older_q[resolve_id_i];', "released_o = valid_q & (8'hff << resolve_id_i);", 1),
            'recover_accumulates': ('rtl/backend/rename_checkpoints.sv', 'history_q[slot] & ~reclaim_o;', '(history_q[slot] & ~reclaim_o) | allocation_i;', 1),
            'unpruned_history': ('rtl/backend/rename_checkpoints.sv', 'history_q[slot] & ~reclaim_o', 'history_q[slot] | reclaim_o', 1),
            'correct_kills_younger': ('rtl/backend/rename_checkpoints.sv', 'released_o[resolve_id_i] = 1;', 'released_o = valid_q;', 1),
            'missing_flush': ('rtl/backend/rename_checkpoints.sv', 'if (rst_i || flush_i) valid_d = 0;', 'if (rst_i) valid_d = 0;', 1),
            'self_ancestor': ('rtl/backend/rename_checkpoints.sv', 'older_d[candidate] = valid_q & ~released_o;', "older_d[candidate] = (valid_q & ~released_o) | (8'b1 << candidate);", 1),
        },
    ),
    'rename_recovery': dict(
        top='rename_recovery', sources=[],
        inputs=['config/rename_state.json', 'config/rename_bundle.json', 'config/rename_checkpoints.json'],
        headers=[], schema_checks=[], parameters={},
        timeout=300, random_key='random_cycles_per_seed', prefix='RENAME RECOVERY PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('cycles') != config['directed_cycles'] + config['random_cycles_per_seed']),
        required=['commit_rename', 'commit_suppressed', 'created', 'cut', 'deferred_tag_reuse', 'flush_collision', 'full_flush', 'full_non_cfi', 'full_stall', 'killed_wb', 'lane1_cfi', 'live_reset', 'nested', 'physical_stall', 'recovery', 'reject_free', 'reject_ready', 'reject_resolve', 'reject_stale', 'reject_zero', 'resolve_create', 'resource_stall', 'retained_wb', 'waw', 'younger_kill'],
        negatives={'commit_prefix': (['negative', 'commit_prefix'], 'RENAME_STATE_COMMIT_PREFIX'), 'wrong_stale': (['negative', 'wrong_stale'], 'RENAME_STATE_COMMIT_OWNER')}, guards={}, extra_runs=[(['1', '0'], 'directed.log')],
        mutation_args=['1', '0'], mismatch='rename recovery mismatch', mutation_flags=['-DSYNTHESIS'],
        mutations={
            'pre_cfi_snapshot': ('rtl/backend/rename_recovery.sv', 'snapshot[rd_i[lane*5 +: 5]*6 +: 6] = destination_o[lane*6 +: 6];', 'snapshot[rd_i[lane*5 +: 5]*6 +: 6] = rat_o[rd_i[lane*5 +: 5]*6 +: 6];', 1),
            'ignore_checkpoint_credit': ('rtl/backend/rename_recovery.sv', '(!needs_checkpoint || checkpoint_ready)', '(needs_checkpoint || checkpoint_ready || !needs_checkpoint)', 1),
            'commit_during_recovery': ('rtl/backend/rename_recovery.sv', 'rst_i || recover_i || branch_recover_o ?', 'rst_i || recover_i ?', 1),
            'accept_killed_writeback': ('rtl/backend/rename_recovery.sv', '&& !reclaim_o[wb_destination_i[lane*6 +: 6]]', '&& (reclaim_o[0] == 0)', 1),
            'drop_surviving_writeback': ('rtl/backend/rename_recovery.sv', 'if (!rst_i && !recover_i && wb_offer_i[lane]', 'if (!rst_i && !recover_i && !branch_recover_o && wb_offer_i[lane]', 1),
            'ignore_wb_identity': ('rtl/backend/rename_recovery.sv', 'wb_offer_i[lane] && wb_live_i[lane]', 'wb_offer_i[lane] && (wb_live_i[lane] || wb_offer_i[lane])', 1),
            'ignore_resolve_identity': ('rtl/backend/rename_recovery.sv', 'resolve_i && resolve_live_i &&', 'resolve_i && (resolve_live_i || resolve_i) &&', 1),
            'replace_current_free': ('rtl/backend/rename_state.sv', 'free_d = free_q | branch_reclaim_i;', 'free_d = branch_reclaim_i;', 1),
            'mark_survivors_ready': ('rtl/backend/rename_state.sv', 'ready_d = ready_view & ~branch_reclaim_i;', 'ready_d = ~free_q & ~branch_reclaim_i;', 1),
            'restore_committed_instead': ('rtl/backend/rename_state.sv', 'rat_d = branch_rat_i;', 'rat_d = branch_rat_i[5:0] == 0 ? committed_q : branch_rat_i;', 1),
        },
    ),
    'rob_two_wide': dict(
        top='rob_two_wide', sources=['rtl/generated/commit_event_pkg.sv', 'rtl/backend/rob_two_wide.sv'],
        inputs=['config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=[], schema_checks=['event-check'], parameters={},
        timeout=600, random_key='random_cycles_per_seed', prefix='ROB TWO WIDE PASS ',
        geometry=lambda config: not ((config['entries'], config['identity_bits']) != (32, 13)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('directed') != config['directed_cycles'] or fields.get('cycles') != fields['directed'] + config['random_cycles_per_seed']),
        required=['backpressure', 'drain', 'dual_allocate', 'dual_complete', 'dual_retire', 'duplicate', 'flush_live', 'full', 'out_of_order', 'recovery', 'recovery_complete', 'recovery_suppression', 'recovery_wrap', 'reset_live', 'resolution_complete', 'simultaneous', 'slot_wrap', 'solo', 'stale', 'stale_resolution', 'trap', 'trap_priority', 'unresolved', 'wrap_block'],
        negatives={'drain_live': (['negative', 'drain_live'], 'ROB2_DRAIN'), 'complete_stale': (['negative', 'complete_stale'], 'ROB2_COMPLETE'), 'resolve_stale': (['negative', 'resolve_stale'], 'ROB2_RESOLVE'), 'retire_unready': (['negative', 'retire_unready'], 'ROB2_RETIRE'), 'trap_unready': (['negative', 'trap_unready'], 'ROB2_TRAP')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='rob two wide mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'generation_alias': ('rtl/backend/rob_two_wide.sv', 'generation_q[complete_id_i[lane*13 +: 5]] == complete_id_i[lane*13+5 +: 8]', "1'b1", 1),
            'resolve_generation_alias': ('rtl/backend/rob_two_wide.sv', 'generation_q[resolve_slot] == resolve_id_i[12:5]', "1'b1", 1),
            'numeric_age': ('rtl/backend/rob_two_wide.sv', "5'(complete_id_i[lane*13 +: 5] - head_q) <= resolve_age", 'complete_id_i[lane*13 +: 5] <= resolve_slot', 1),
            'numeric_squash': ('rtl/backend/rob_two_wide.sv', "5'(5'(slot) - head_q) > resolve_age", "5'(slot) > resolve_slot", 1),
            'duplicate_completion': ('rtl/backend/rob_two_wide.sv', 'complete_ready_o[1] = 0;', 'complete_ready_o[1] = complete_ready_o[1];', 1),
            'unresolved_retirement': ('rtl/backend/rob_two_wide.sv', '(!cfi_q[head_q] || resolved_q[head_q])', "1'b1", 1),
            'solo_pair': ('rtl/backend/rob_two_wide.sv', '&& !solo_q[head_q] && !solo_q[second_head]', '', 1),
            'wrong_event': ('rtl/backend/rob_two_wide.sv', '<= complete_event_i[lane];', '<= complete_event_i[1-lane];', 1),
            'wrong_order': ('rtl/backend/rob_two_wide.sv', "order_q + 64'(lane)", "order_q + 64'(lane) + 64'd1", 1),
            'generation_wrap': ('rtl/backend/rob_two_wide.sv', 'count_q < 32 && !exhausted_q[tail_q]', 'count_q < 32', 1),
        },
    ),
    'backend_two_wide': dict(
        top='backend_two_wide', sources=[],
        inputs=['verif/unit/backend_reference.hpp', 'config/rob_two_wide.json', 'config/rename_recovery.json', 'config/prf_contract.json', 'config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=['event'], schema_checks=['event-check'], parameters={},
        timeout=600, random_key='random_cycles_per_seed', prefix='BACKEND TWO WIDE PASS ',
        geometry=lambda config: not ((config['entries'], config['identity_bits']) != (32, 13)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('directed') != config['directed_cycles'] or fields.get('cycles') != fields['directed'] + config['random_cycles_per_seed']),
        required=['checkpoint_full', 'checkpoint_reuse', 'drain', 'dual_allocate', 'dual_complete', 'dual_retire', 'duplicate', 'fault_no_write', 'flush_live', 'generation_stall', 'late_solo', 'nested_recovery', 'prf_bypass', 'prf_full', 'raw', 'read_reclaim', 'recovery', 'recovery_wrap', 'reset_live', 'resultless', 'rob_full', 'simultaneous', 'solo_retire', 'stale', 'stale_resolve', 'stalled_retire', 'surviving_wb', 'trap', 'waw'],
        negatives={'offered_drain': (['negative', 'offered_drain'], 'BACKEND_DRAIN')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='backend two wide mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'lost_late_solo': ('rtl/backend/backend_two_wide.sv', '.complete_solo_i,', ".complete_solo_i(2'b00),", 1),
            'reclaimed_read_ready': ('rtl/backend/backend_two_wide.sv', '&& !reclaim[read_address_i[port_id*6 +: 6]]', '', 1),
            'stale_write': ('rtl/backend/backend_two_wide.sv', '.wb_live_i(wb_live)', ".wb_live_i(2'b11)", 1),
            'unqualified_prf': ('rtl/backend/backend_two_wide.sv', '.wb_accept_i(wb_accept_o)', '.wb_accept_i(complete_offer_i)', 1),
            'lost_second_write': ('rtl/backend/backend_two_wide.sv', '.wb_accept_i(wb_accept_o)', ".wb_accept_i(wb_accept_o & 2'b01)", 1),
            'swapped_payload': ('rtl/backend/backend_two_wide.sv', '{complete_event_i[1].rd_value, complete_event_i[0].rd_value}', '{complete_event_i[0].rd_value, complete_event_i[1].rd_value}', 1),
            'wrong_checkpoint': ('rtl/backend/backend_two_wide.sv', '<= checkpoint_id_o;', "<= checkpoint_id_o ^ 3'd1;", 1),
            'ignored_sink': ('rtl/backend/backend_two_wide.sv', 'retire_valid_o[0] && retire_ready_i[0]', 'retire_valid_o[0]', 1),
            'lost_trap_restore': ('rtl/backend/backend_two_wide.sv', 'wire recover = flush_i || trap_accept_o;', 'wire recover = flush_i;', 1),
            'lost_second_commit': ('rtl/backend/backend_two_wide.sv', '.commit_i(commit_request)', ".commit_i(commit_request & 2'b01)", 1),
            'ignored_rob_credits': ('rtl/backend/backend_two_wide.sv', '&& (selected & ~rob_allocate_ready) == 0', '', 1),
            'stale_resolution': ('rtl/backend/backend_two_wide.sv', '.resolve_live_i(rob_resolve_ready)', ".resolve_live_i(1'b1)", 1),
        },
    ),
    'issue_queue': dict(
        top='issue_queue', sources=[],
        inputs=['config/backend_two_wide.json', 'config/rob_two_wide.json', 'config/prf_contract.json'],
        headers=[], schema_checks=[], parameters={},
        timeout=600, random_key='random_cycles_per_seed', prefix='ISSUE QUEUE PASS ',
        geometry=lambda config: not ((config['entries'], config['rob_entries'], config['identity_bits'], config['payload_bits']) != (16, 32, 13, 64)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('directed') != config['directed_cycles'] or fields.get('cycles') != fields['directed'] + config['random_cycles_per_seed']),
        required=['backpressure', 'dispatch_issue', 'dispatch_wb', 'dual_dispatch', 'dual_issue', 'dual_wakeup', 'flush_live', 'full', 'generation_forwarded', 'one_credit', 'port0_only', 'port1_only', 'recovery', 'recovery_killed', 'recovery_survivor', 'recovery_wakeup', 'recovery_wrap', 'reset_live', 'retained_wakeup', 'same_source', 'stalled_wakeup', 'unaccepted_broadcast', 'wakeup_issue', 'wrapped_window', 'zero_source'],
        negatives={'prefix': (['negative', 'prefix'], 'IQ_DISPATCH'), 'overflow': (['negative', 'overflow'], 'IQ_DISPATCH'), 'eligibility': (['negative', 'eligibility'], 'IQ_ELIGIBILITY'), 'identity': (['negative', 'identity'], 'IQ_IDENTITY')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='issue queue mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'raw_broadcast': ('rtl/backend/issue_queue.sv', 'wb_accept_i[lane] &&', "1'b1 &&", 1),
            'lost_second_wakeup': ('rtl/backend/issue_queue.sv', 'wb_accept_i[lane] &&', 'wb_accept_i[lane] && lane == 0 &&', 1),
            'lost_wakeup_retention': ('rtl/backend/issue_queue.sv', 'if (valid_q[slot]) ready_q[slot] <= awake[slot];', '', 1),
            'raw_slot_age': ('rtl/backend/issue_queue.sv', "5'(id_q[slot][4:0] - head_slot_i)", 'id_q[slot][4:0]', 3),
            'youngest_first': ('rtl/backend/issue_queue.sv', '< best_age[port_id]', '> best_age[port_id]', 1),
            'duplicate_issue': ('rtl/backend/issue_queue.sv', '(port_id == 0 || !chosen[0][slot])', "1'b1", 1),
            'ignored_backpressure': ('rtl/backend/issue_queue.sv', '&& port_ready_i[port_id]', '', 1),
            'ignored_eligibility': ('rtl/backend/issue_queue.sv', '&& eligible_q[slot][port_id]', '', 1),
            'lost_second_dispatch': ('rtl/backend/issue_queue.sv', 'if (!stop && dispatch_i[lane])', 'if (!stop && dispatch_i[lane] && lane == 0)', 1),
            'lost_recovery_kill': ('rtl/backend/issue_queue.sv', 'valid_q[slot] <= 0;\n        if (chosen', 'valid_q[slot] <= valid_q[slot];\n        if (chosen', 1),
            'unsigned_recovery_cut': ('rtl/backend/issue_queue.sv', "5'(id_q[slot][4:0] - head_slot_i) > 5'(recover_slot_i - head_slot_i)", 'id_q[slot][4:0] > recover_slot_i', 1),
            'recovery_launch': ('rtl/backend/issue_queue.sv', 'rst_i || flush_i || recover_i', 'rst_i || flush_i', 1),
            'lost_generation': ('rtl/backend/issue_queue.sv', '= id_q[slot];', "= {8'b0, id_q[slot][4:0]};", 1),
            'lost_payload': ('rtl/backend/issue_queue.sv', '= payload_q[slot];', "= payload_q[slot] ^ 64'd1;", 1),
        },
    ),
    'issue_backend': dict(
        top='issue_backend', sources=[],
        inputs=['config/backend_two_wide.json', 'config/issue_queue.json', 'config/rob_two_wide.json', 'config/prf_contract.json', 'config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=['event'], schema_checks=['event-check'], parameters={},
        timeout=900, random_key='random_cycles_per_seed', prefix='ISSUE BACKEND PASS ',
        geometry=lambda config: not ((config['queue_entries'], config['rob_entries'], config['identity_bits'], config['payload_bits']) != (16, 32, 13, 64)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('directed') != config['directed_cycles'] or fields.get('cycles') != fields['directed'] + config['random_cycles_per_seed']),
        required=['backpressure', 'branch_issue', 'dispatch_issue', 'drain', 'dual_allocate', 'dual_complete', 'dual_issue', 'dual_retire', 'fault_no_write', 'flush_live', 'nested_recovery', 'port0_only', 'port1_only', 'prf_bypass', 'prf_full', 'queue_full', 'queue_stall', 'recovery', 'recovery_killed', 'recovery_survivor', 'reset_live', 'resolution_after_issue', 'resultless', 'retained_wakeup', 'rob_full', 'simultaneous', 'simultaneous_checkpoint_create_resolve', 'stalled_wakeup', 'surviving_wb', 'trap', 'trap_live', 'unaccepted_broadcast', 'wakeup_issue', 'wrapped_window', 'zero_source'],
        negatives={'eligibility': (['negative', 'eligibility'], 'IQ_ELIGIBILITY'), 'offered_drain': (['negative', 'offered_drain'], 'ISSUE_BACKEND_DRAIN')}, guards={'branch_before_issue': (['negative', 'branch_before_issue'], 'stimulus resolution before issue'), 'branch_port': (['negative', 'branch_port'], 'stimulus branch port')}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='issue backend mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'lost_queue_credit': ('rtl/backend/issue_backend.sv', ' && (selected & ~queue_skip_i & ~dispatch_ready) == 0', '', 1),
            'lost_second_credit': ('rtl/backend/issue_backend.sv', '(selected & ~queue_skip_i & ~dispatch_ready) == 0', '(selected[0] & ~queue_skip_i[0] & ~dispatch_ready[0]) == 0', 1),
            'unselected_prefix': ('rtl/backend/issue_backend.sv', 'valid_i[1] && !cfi_i[0]', 'valid_i[1]', 1),
            'unaccepted_dispatch': ('rtl/backend/issue_backend.sv', '.dispatch_i(allocate_accept_o & ~queue_skip_i)', '.dispatch_i(valid_i & ~queue_skip_i)', 1),
            'lost_dispatch_readiness': ('rtl/backend/issue_backend.sv', '.dispatch_ready_i(source_ready_o)', ".dispatch_ready_i(4'b1111)", 1),
            'lost_issue_destination': ('rtl/backend/issue_backend.sv', '.dispatch_destination_i(destination_o)', ".dispatch_destination_i(12'd0)", 1),
            'lost_payload': ('rtl/backend/issue_backend.sv', '.dispatch_payload_i(payload_i)', ".dispatch_payload_i(128'd0)", 1),
            'swapped_sources': ('rtl/backend/issue_backend.sv', '{source2_o[11:6], source1_o[11:6], source2_o[5:0], source1_o[5:0]}', '{source1_o[11:6], source2_o[11:6], source1_o[5:0], source2_o[5:0]}', 1),
            'swapped_dispatch_identity': ('rtl/backend/issue_backend.sv', '.dispatch_id_i(allocate_id_o)', '.dispatch_id_i({allocate_id_o[12:0], allocate_id_o[25:13]})', 1),
            'swapped_eligibility': ('rtl/backend/issue_backend.sv', '.dispatch_eligible_i(eligible_i)', '.dispatch_eligible_i({eligible_i[1:0], eligible_i[3:2]})', 1),
            'renamed_wakeup_tag': ('rtl/backend/issue_backend.sv', '.wb_destination_i(wb_destination_o)', '.wb_destination_i(destination_o)', 1),
            'raw_wakeup': ('rtl/backend/issue_backend.sv', '.wb_accept_i(wb_accept_o)', '.wb_accept_i(complete_offer_i)', 1),
            'lost_wakeup': ('rtl/backend/issue_backend.sv', '.wb_accept_i(wb_accept_o)', ".wb_accept_i(2'b00)", 1),
            'unconnected_read': ('rtl/backend/issue_backend.sv', '.read_address_i(read_address)', ".read_address_i(24'd0)", 1),
            'wrong_head_slot': ('rtl/backend/issue_backend.sv', '.head_slot_i(head_id_o[4:0])', ".head_slot_i(5'd0)", 1),
            'wrong_recover_slot': ('rtl/backend/issue_backend.sv', '.recover_slot_i(resolve_id_i[4:0])', '.recover_slot_i(head_id_o[4:0])', 1),
            'lost_branch_kill': ('rtl/backend/issue_backend.sv', '.recover_i(branch_recover_o)', ".recover_i(1'b0)", 1),
            'lost_trap_flush': ('rtl/backend/issue_backend.sv', '.flush_i(recover)', '.flush_i(flush_i)', 1),
        },
    ),
    'integer_backend': dict(
        top='integer_backend', sources=[],
        inputs=['config/integer_backend.vlt', 'config/issue_backend.json', 'config/backend_two_wide.json', 'config/issue_queue.json', 'config/rob_two_wide.json', 'config/prf_contract.json', 'config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=['event'], schema_checks=['event-check'], parameters={},
        timeout=900, random_key='random_cycles_per_seed', prefix='INTEGER BACKEND PASS ',
        geometry=lambda config: not ((config['queue_entries'], config['rob_entries'], config['identity_bits'], config['physical_registers'], config['producer_slots']) != (16, 32, 13, 64, 2)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('directed') != config['directed_cycles'] or fields.get('cycles') != fields['directed'] + config['random_cycles_per_seed'] + fields.get('final_drain', 0) or (fields.get('random') != config['random_cycles_per_seed']) or (fields.get('final_drain', 0) < 1)),
        required=['bundle_raw', 'bundle_waw', 'completion_stall', 'consume_refill', 'drain', 'dual_allocate', 'dual_complete', 'dual_issue', 'dual_retire', 'flush_held', 'generation_stall', 'issue_stall', 'op_0', 'op_1', 'op_10', 'op_11', 'op_12', 'op_13', 'op_14', 'op_15', 'op_16', 'op_17', 'op_18', 'op_19', 'op_2', 'op_20', 'op_3', 'op_4', 'op_5', 'op_6', 'op_7', 'op_8', 'op_9', 'out_of_order_complete', 'out_of_order_issue', 'queue_full', 'reset_held', 'resultless', 'retire_stall', 'retired', 'rob_full', 'unsupported', 'wakeup_bypass', 'wrapped_window'],
        negatives={'prefix': (['negative', 'prefix'], 'INTEGER_PREFIX'), 'held_drain': (['negative', 'held_drain'], 'INTEGER_DRAIN')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='integer backend mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'lost_hold': ('rtl/execute/alu_pipeline.sv', 'if (take_i) pending_q <= 0;', 'pending_q <= 0;', 1),
            'lost_refill': ('rtl/execute/alu_pipeline.sv', '(!pending_q || take_i)', '!pending_q', 1),
            'lost_identity': ('rtl/execute/alu_pipeline.sv', 'id_o <= id_i;', "id_o <= 13'd0;", 1),
            'wrong_result': ('rtl/execute/alu_pipeline.sv', 'built.rd_value = result;', "built.rd_value = result ^ 32'd1;", 1),
            'wrong_next_pc': ('rtl/execute/alu_pipeline.sv', 'built.pc_after = next_pc;', 'built.pc_after = pc_i;', 1),
            'wrong_source_event': ('rtl/execute/alu_pipeline.sv', 'built.rs1_value = source1_i;', "built.rs1_value = source1_i ^ 32'd1;", 1),
            'lost_second_launch': ('rtl/backend/integer_backend.sv', '.launch_i(issue_o[lane])', '.launch_i(issue_o[lane] && lane == 0)', 1),
            'swapped_operands': ('rtl/backend/integer_backend.sv', '.source1_i(read_data[lane*64 +: 32])', '.source1_i(read_data[lane*64+32 +: 32])', 1),
            'swapped_pc': ('rtl/backend/integer_backend.sv', '.pc_i(issue_payload[lane*64+32 +: 32])', '.pc_i(issue_payload[lane*64 +: 32])', 1),
            'ignored_completion_grant': ('rtl/backend/integer_backend.sv', 'completion_valid_o & completion_enable_i', 'completion_valid_o', 1),
            'ignored_execution_stall': ('rtl/backend/integer_backend.sv', 'producer_ready && execution_ready_i[lane]', 'producer_ready', 1),
            'unsupported_dispatch': ('rtl/backend/integer_backend.sv', '.resources_ready_i((valid_i & ~supported_o) == 0)', ".resources_ready_i(1'b1)", 1),
            'raw_completion_release': ('rtl/backend/integer_backend.sv', '.take_i(completion_accept_o[lane])', '.take_i(completion_valid_o[lane])', 1),
            'lost_producer_flush': ('rtl/backend/integer_backend.sv', '.clk_i, .rst_i, .flush_i, .launch_i', ".clk_i, .rst_i, .flush_i(1'b0), .launch_i", 1),
        },
    ),
    'control_flow_backend': dict(
        top='control_flow_backend', sources=[],
        inputs=['config/control_flow_backend.vlt', 'config/issue_backend.json', 'config/backend_two_wide.json', 'config/issue_queue.json', 'config/rob_two_wide.json', 'config/prf_contract.json', 'config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=['event'], schema_checks=['event-check'], parameters={},
        timeout=900, random_key='random_cycles_per_seed', prefix='CONTROL FLOW BACKEND PASS ',
        geometry=lambda config: not ((config['queue_entries'], config['rob_entries'], config['identity_bits'], config['physical_registers'], config['producer_slots'], config['checkpoints']) != (16, 32, 13, 64, 2, 8)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('directed') != config['directed_cycles'] or fields.get('cycles') != fields['directed'] + config['random_cycles_per_seed'] + fields.get('final_drain', 0) or (fields.get('random') != config['random_cycles_per_seed']) or (fields.get('final_drain', 0) < 1)),
        required=['branch_launch', 'bundle_raw', 'bundle_waw', 'cfi_lane1', 'cfi_prefix', 'checkpoint_full', 'checkpoint_reuse', 'completion_stall', 'consume_refill', 'direction_only_prediction', 'drain', 'dual_allocate', 'dual_complete', 'dual_issue', 'dual_retire', 'fault_complete', 'fault_op_21', 'fault_op_27', 'fault_op_28', 'flush_held', 'generation_stall', 'head_fault', 'ignored_tail_unsupported', 'jalr_lsb_cleared', 'kill_completed', 'kill_fault', 'kill_held', 'kill_queued', 'kill_resolved_branch', 'nested_resolve', 'not_taken', 'op_0', 'op_1', 'op_10', 'op_11', 'op_12', 'op_13', 'op_14', 'op_15', 'op_16', 'op_17', 'op_18', 'op_19', 'op_2', 'op_20', 'op_21', 'op_22', 'op_23', 'op_24', 'op_25', 'op_26', 'op_27', 'op_28', 'op_3', 'op_4', 'op_5', 'op_6', 'op_7', 'op_8', 'op_9', 'out_of_order_complete', 'out_of_order_issue', 'prediction_right', 'prediction_wrong', 'queue_full', 'reset_held', 'resolution_blocks_completion', 'resolution_stall', 'resolve_allocate', 'resolve_completion_stall', 'resultless', 'retire_stall', 'retired', 'rob_full', 'surviving_held', 'surviving_wb', 'taken', 'unsupported', 'wakeup_bypass', 'wrapped_recovery', 'wrapped_window'],
        negatives={'prefix': (['negative', 'prefix'], 'CF_BACKEND_PREFIX'), 'unresolved_drain': (['negative', 'unresolved_drain'], 'CF_BACKEND_DRAIN')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='control flow backend mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'early_completion': ('rtl/execute/control_flow_pipeline.sv', '(!cfi_q || event_o.trap || resolved_q)', "1'b1", 1),
            'repeat_resolution': ('rtl/execute/control_flow_pipeline.sv', '&& !event_o.trap && !resolved_q', '&& !event_o.trap', 1),
            'ignored_resolution_grant': ('rtl/backend/control_flow_backend.sv', '.resolve_grant_i(resolve_grant_i && !(SYSTEM_SERVICE && (system_busy_o || fault_pending_o)))', '.resolve_grant_i(!(SYSTEM_SERVICE && (system_busy_o || fault_pending_o)))', 1),
            'live_prediction_pc': ('rtl/backend/control_flow_backend.sv', '.predicted_pc_i(prediction_pc_q[issue_id_o[4:0]])', '.predicted_pc_i(predicted_pc_i[31:0])', 1),
            'live_prediction_taken': ('rtl/backend/control_flow_backend.sv', '.predicted_taken_i(prediction_taken_q[issue_id_o[4:0]])', '.predicted_taken_i(predicted_taken_i[0])', 1),
            'lost_lane1_prediction': ('rtl/backend/control_flow_backend.sv', 'allocate_accept_o[lane] && cfi[lane]', 'allocate_accept_o[lane] && cfi[lane] && lane == 0', 1),
            'lost_direction_mismatch': ('rtl/execute/control_flow_pipeline.sv', 'predicted_taken_i != taken || predicted_pc_i != next_pc', 'predicted_pc_i != next_pc', 1),
            'wrong_next_pc': ('rtl/execute/control_flow_pipeline.sv', 'built.pc_after = next_pc;', "built.pc_after = pc_i + 32'd4;", 1),
            'unsigned_branch_direction': ('rtl/execute/control_flow_pipeline.sv', 'taken = $signed(source1_i) < $signed(source2_i);', 'taken = source1_i < source2_i;', 1),
            'fault_link_write': ('rtl/execute/control_flow_pipeline.sv', '!execute_trap && decoded.rd != 0', 'decoded.rd != 0', 1),
            'lost_fault_target': ('rtl/execute/control_flow_pipeline.sv', 'built.trap_value = trap_value;', "built.trap_value = 32'd0;", 1),
            'lost_result_hold': ('rtl/execute/control_flow_pipeline.sv', 'if (take_i) pending_q <= 0;', 'pending_q <= 0;', 1),
            'lost_full_flush': ('rtl/execute/control_flow_pipeline.sv', 'if (rst_i || flush_i) begin', 'if (rst_i) begin', 1),
            'lost_selective_cancel': ('rtl/backend/control_flow_backend.sv', '.flush_i(producer_flush || cancel_alu1)', '.flush_i(producer_flush)', 1),
            'raw_slot_age': ('rtl/backend/control_flow_backend.sv', "5'(completion_id_o[17:13] - head_id_o[4:0])\n      > 5'(resolve_id_o[4:0] - head_id_o[4:0])", 'completion_id_o[17:13] > resolve_id_o[4:0]', 1),
            'cancel_before_grant': ('rtl/backend/control_flow_backend.sv', 'wire cancel_alu1 = redirect_o &&', 'wire cancel_alu1 = resolve_valid_o && resolve_mispredict_o &&', 1),
            'cancel_older': ('rtl/backend/control_flow_backend.sv', "> 5'(resolve_id_o[4:0] - head_id_o[4:0])", "< 5'(resolve_id_o[4:0] - head_id_o[4:0])", 1),
            'lost_cfi_eligibility': ('rtl/backend/control_flow_backend.sv', "cfi[lane] ? 2'b01 : 2'b11", "2'b11", 1),
            'lost_cfi_allocation': ('rtl/backend/control_flow_backend.sv', '.cfi_i(cfi)', ".cfi_i(2'b00)", 1),
            'wrong_resolver_identity': ('rtl/backend/control_flow_backend.sv', 'assign resolve_id_o = completion_id_o[12:0];', 'assign resolve_id_o = completion_id_o[25:13];', 1),
            'release_on_resolution': ('rtl/backend/control_flow_backend.sv', '.take_i(completion_accept_o[0])', '.take_i(resolve_accept_o)', 1),
        },
    ),
    'fetch_two_wide': dict(
        top='fetch_two_wide', sources=[],
        inputs=['config/fetch_two_wide.vlt', 'config/platform.yaml', 'config/memory_protocol.yaml', 'tools/gen_platform.py', 'tools/gen_memory_protocol.py'],
        headers=['memory'], schema_checks=['platform-check', 'memory-check'], parameters={},
        timeout=900, random_key='random_cycles_per_seed', prefix='FETCH TWO WIDE PASS ',
        geometry=lambda config: not ((config['line_bytes'], config['outstanding'], config['lanes']) != (32, 1, 2)),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('random') != config['random_cycles_per_seed'] or fields.get('directed', 0) < 500 or (fields.get('cycles') != fields['directed'] + fields['random'] + 8)),
        required=['alignment_fault', 'bus_fault', 'consume', 'disabled_buffer', 'disabled_empty', 'discard_data', 'discard_fault', 'dual_take', 'fatal_hold', 'fault_take', 'fill', 'id_wrap', 'line_tail', 'malformed', 'malformed_0', 'malformed_1', 'malformed_2', 'malformed_3', 'malformed_4', 'malformed_5', 'malformed_6', 'malformed_7', 'offset_0', 'offset_1', 'offset_2', 'offset_3', 'offset_4', 'offset_5', 'offset_6', 'offset_7', 'output_stall', 'partial_pair', 'pma_fault', 'redirect_buffered', 'redirect_empty', 'redirect_handshake', 'redirect_offered', 'redirect_pending', 'redirect_response', 'redirect_response_fault', 'redirect_stopped', 'repeated_redirect', 'request', 'request_stall', 'reset_buffered', 'reset_idle', 'reset_offered', 'reset_pending'],
        negatives={'prefix': (['negative'], 'FETCH_PREFIX'), 'empty': (['negative', 'empty'], 'FETCH_PREFIX')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='fetch two wide mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'disabled_request': ('rtl/frontend/fetch_two_wide.sv', 'enable_i && !redirect_i', '!redirect_i', 1),
            'withdraw_request': ('rtl/frontend/fetch_two_wide.sv', 'active && state_q == REQUEST;', 'active && state_q == REQUEST && !redirect_i;', 1),
            'live_request_pc': ('rtl/frontend/fetch_two_wide.sv', "{request_line_q, 5'd0}", "{pc_q[31:5], 5'd0}", 1),
            'discard_lost': ('rtl/frontend/fetch_two_wide.sv', 'if (discard_q || redirect_i)', 'if (redirect_i)', 1),
            'redirect_response_lost': ('rtl/frontend/fetch_two_wide.sv', 'if (discard_q || redirect_i)', 'if (discard_q)', 1),
            'first_redirect_only': ('rtl/frontend/fetch_two_wide.sv', 'pc_q <= redirect_pc_i;', 'if (!discard_q) pc_q <= redirect_pc_i;', 1),
            'redirect_output_visible': ('rtl/frontend/fetch_two_wide.sv', 'if (active && !redirect_i)', 'if (active)', 1),
            'partial_pair_skipped': ('rtl/frontend/fetch_two_wide.sv', "take_i[1] ? 32'd8 : 32'd4", "32'd8", 1),
            'line_tail_second_lane': ('rtl/frontend/fetch_two_wide.sv', "pc_q[4:2] == 3'd7 ? 2'b01 : 2'b11", "2'b11", 1),
            'word_reversed': ('rtl/frontend/fetch_two_wide.sv', 'line_q[pc_q[4:2]*32 +: 32]', "line_q[(7-int'(pc_q[4:2]))*32 +: 32]", 1),
            'id_not_advanced': ('rtl/frontend/fetch_two_wide.sv', "id_q <= id_q + 1'b1;", 'id_q <= id_q;', 1),
            'wrong_id_accepted': ('rtl/frontend/fetch_two_wide.sv', '|| response_i.transaction_id != id_q', '', 1),
            'uncached_data_accepted': ('rtl/frontend/fetch_two_wide.sv', '|| response_i.uncached_read_data != 0', '', 1),
            'fault_data_accepted': ('rtl/frontend/fetch_two_wide.sv', '|| (response_i.status != MEM_STATUS_OK && response_i.line_read_data != 0)', '', 1),
            'reserved_status_accepted': ('rtl/frontend/fetch_two_wide.sv', 'MEM_STATUS_OK, MEM_STATUS_ACCESS_FAULT}', 'MEM_STATUS_OK, MEM_STATUS_ACCESS_FAULT, MEM_STATUS_PROTOCOL_ERROR}', 1),
            'stale_protocol_unchecked': ('rtl/frontend/fetch_two_wide.sv', 'if (malformed) fatal_o <= 1;', 'if (malformed && !discard_q) fatal_o <= 1;', 1),
            'fault_repeated': ('rtl/frontend/fetch_two_wide.sv', 'state_q <= STOP;', 'state_q <= FAULT;', 1),
            'alignment_cause_lost': ('rtl/frontend/fetch_two_wide.sv', 'assign fault_cause_o = misaligned_q ?', "assign fault_cause_o = 1'b0 ?", 1),
            'fatal_clear_redirect': ('rtl/frontend/fetch_two_wide.sv', 'end else if (!fatal_o) begin', 'end else if (!fatal_o || redirect_i) begin\n      fatal_o <= 0;', 1),
        },
    ),
    'fetch_execution_core': dict(
        top='fetch_execution_core', sources=[],
        inputs=['verif/unit/fetch_execution_reference.hpp', 'config/fetch_execution_core.vlt', 'config/platform.yaml', 'config/memory_protocol.yaml', 'config/commit_event.yaml', 'config/control_flow_backend.json', 'config/fetch_two_wide.json', 'config/issue_backend.json', 'config/backend_two_wide.json', 'config/issue_queue.json', 'config/rob_two_wide.json', 'config/prf_contract.json', 'tools/gen_platform.py', 'tools/gen_memory_protocol.py', 'tools/gen_commit_event.py'],
        headers=['event', 'memory', 'csr'], schema_checks=['platform-check', 'memory-check', 'event-check'], parameters={'FRONTEND_FAULTS': 0, 'TRAP_SERVICE': 0},
        timeout=900, random_key=None, prefix='FETCH EXECUTION CORE PASS ',
        geometry=lambda config: not (config['parameters'] != {'FRONTEND_FAULTS': 0, 'TRAP_SERVICE': 0}),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('retired', 0) < 5000 or fields.get('cycles', 0) < 10000),
        required=['backend_fault', 'branch_redirect', 'completion_stall', 'dispatch_stall', 'drain', 'dual_dispatch', 'dual_retire', 'external_flush', 'fatal_injected', 'frontend_alignment', 'frontend_bus_fault', 'frontend_pma', 'not_taken', 'op_0', 'op_1', 'op_10', 'op_11', 'op_12', 'op_13', 'op_14', 'op_15', 'op_16', 'op_17', 'op_18', 'op_19', 'op_2', 'op_20', 'op_21', 'op_22', 'op_23', 'op_24', 'op_25', 'op_26', 'op_27', 'op_28', 'op_3', 'op_4', 'op_5', 'op_6', 'op_7', 'op_8', 'op_9', 'redirect_pending', 'redirect_request_stall', 'request_stall', 'reset', 'retire_stall', 'rob_full', 'taken', 'unsupported', 'wrong_path_fault_recovered'],
        negatives={'drain': (['negative'], 'FETCH_CORE_DRAIN')}, guards={}, extra_runs=[],
        mutation_args=['1'], mismatch='fetch execution core mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'lost_fetch_consume': ('rtl/core/fetch_execution_core.sv', '.take_i(dispatch_o)', ".take_i(2'b00)", 1),
            'consume_before_dispatch': ('rtl/core/fetch_execution_core.sv', '.take_i(dispatch_o)', '.take_i(fetch_valid_o & {2{!fetch_fault_o}})', 1),
            'wrong_prediction_pc': ('rtl/core/fetch_execution_core.sv', "fetch_pc_o[63:32] + 32'd4", 'fetch_pc_o[63:32]', 1),
            'taken_prediction': ('rtl/core/fetch_execution_core.sv', ".predicted_taken_i(2'b00)", ".predicted_taken_i(2'b11)", 1),
            'lost_branch_redirect': ('rtl/core/fetch_execution_core.sv', '(flush_i || system_redirect || branch_redirect)', '(flush_i || system_redirect)', 1),
            'wrong_branch_target': ('rtl/core/fetch_execution_core.sv', 'system_pc : branch_pc', "system_pc : 32'd0", 1),
            'lost_backend_flush': ('rtl/core/fetch_execution_core.sv', '.flush_i(flush_i && running)', ".flush_i(1'b0)", 1),
            'lost_external_restart': ('rtl/core/fetch_execution_core.sv', '(flush_i || system_redirect || branch_redirect)', '(system_redirect || branch_redirect)', 1),
            'ignored_resolution_grant': ('rtl/core/fetch_execution_core.sv', '.resolve_grant_i(resolve_grant_i && running)', '.resolve_grant_i(running)', 1),
            'fatal_retirement': ('rtl/core/fetch_execution_core.sv', '.retire_ready_i(retire_ready_i & {2{running}})', '.retire_ready_i(retire_ready_i)', 1),
            'swapped_pc_lanes': ('rtl/core/fetch_execution_core.sv', '.valid_i(backend_valid), .instruction_i(fetch_instruction_o), .pc_i(fetch_pc_o)', '.valid_i(backend_valid), .instruction_i(fetch_instruction_o), .pc_i({fetch_pc_o[31:0], fetch_pc_o[63:32]})', 1),
        },
    ),
    'frontend_faults': dict(
        top='fetch_execution_core', sources=[],
        inputs=['verif/unit/fetch_execution_reference.hpp', 'config/fetch_execution_core.json', 'config/fetch_execution_core.vlt', 'config/platform.yaml', 'config/memory_protocol.yaml', 'config/commit_event.yaml', 'config/control_flow_backend.json', 'config/fetch_two_wide.json', 'config/issue_backend.json', 'config/backend_two_wide.json', 'config/issue_queue.json', 'config/rob_two_wide.json', 'config/prf_contract.json', 'tools/gen_platform.py', 'tools/gen_memory_protocol.py', 'tools/gen_commit_event.py'],
        headers=['event', 'memory', 'csr'], schema_checks=['platform-check', 'memory-check', 'event-check'], parameters={'FRONTEND_FAULTS': 1, 'TRAP_SERVICE': 0},
        timeout=900, random_key=None, prefix='FRONTEND FAULTS PASS ',
        geometry=lambda config: not (config['parameters'] != {'FRONTEND_FAULTS': 1, 'TRAP_SERVICE': 0}),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('retired', 0) < 6000 or fields.get('cycles', 0) < 15000),
        required=['ecall_lane0', 'ecall_lane1', 'ebreak_lane0', 'ebreak_lane1', 'backend_fault', 'bus_offset_0', 'bus_offset_1', 'bus_offset_2', 'bus_offset_3', 'bus_offset_4', 'bus_offset_5', 'bus_offset_6', 'bus_offset_7', 'completion_stall', 'deferred_legal', 'drain', 'dual_dispatch', 'dual_retire', 'fault_offset_0', 'fault_offset_1', 'fault_offset_2', 'fault_offset_3', 'fault_offset_4', 'fault_offset_5', 'fault_offset_6', 'fault_offset_7', 'fault_prefix', 'fetch_fault_dispatch', 'frontend_alignment', 'frontend_bus_fault', 'frontend_pma', 'illegal_lane0', 'illegal_lane1', 'normal_program', 'op_0', 'op_1', 'op_10', 'op_11', 'op_12', 'op_13', 'op_14', 'op_15', 'op_16', 'op_17', 'op_18', 'op_19', 'op_2', 'op_20', 'op_21', 'op_22', 'op_23', 'op_24', 'op_25', 'op_26', 'op_27', 'op_28', 'op_3', 'op_4', 'op_5', 'op_6', 'op_7', 'op_8', 'op_9', 'retire_stall', 'slot_reuse', 'squash_fault_0', 'squash_fault_1', 'squash_fault_2', 'squash_fault_3'],
        negatives={}, guards={}, extra_runs=[],
        mutation_args=['1'], mismatch='fetch execution core mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'ecall_stalls': ('rtl/frontend/frontend_fault_decode.sv', '{OP_ILLEGAL, OP_ECALL, OP_EBREAK}', '{OP_ILLEGAL, OP_EBREAK}', 1),
            'ebreak_stalls': ('rtl/frontend/frontend_fault_decode.sv', '{OP_ILLEGAL, OP_ECALL, OP_EBREAK}', '{OP_ILLEGAL, OP_ECALL}', 1),
            'ecall_cause': ('rtl/frontend/frontend_fault_decode.sv', 'OP_ECALL ? CAUSE_ENVIRONMENT_CALL_FROM_M_MODE', 'OP_ECALL ? CAUSE_ILLEGAL_INSTRUCTION', 1),
            'ebreak_cause': ('rtl/frontend/frontend_fault_decode.sv', 'OP_EBREAK ? CAUSE_BREAKPOINT', 'OP_EBREAK ? CAUSE_ILLEGAL_INSTRUCTION', 1),
            'ecall_value': ('rtl/frontend/frontend_fault_decode.sv', "OP_ECALL ? 32'd0", 'OP_ECALL ? pc_i[lane*32 +: 32]', 1),
            'ebreak_value': ('rtl/frontend/frontend_fault_decode.sv', 'OP_EBREAK ? pc_i[lane*32 +: 32]', "OP_EBREAK ? 32'd0", 1),
            'fault_not_completed': ('rtl/backend/control_flow_backend.sv', 'if (fault_q[completion_id_o[lane*13 +: 5]])', "if (1'b0)", 1),
            'fault_trap_lost': ('rtl/backend/control_flow_backend.sv', 'completion_event_o[lane].trap = 1;', 'completion_event_o[lane].trap = 0;', 1),
            'fault_destination_leak': ('rtl/backend/control_flow_backend.sv', 'completion_event_o[lane].privilege = 3;', 'completion_event_o[lane].privilege = 3; completion_event_o[lane].rd_addr = 1;', 1),
            'wrong_fault_cause': ('rtl/backend/control_flow_backend.sv', 'completion_event_o[lane].trap_cause = fault_cause_q[completion_id_o[lane*13 +: 5]];', 'completion_event_o[lane].trap_cause = 0;', 1),
            'live_fault_value': ('rtl/backend/control_flow_backend.sv', 'completion_event_o[lane].trap_value = fault_value_q[completion_id_o[lane*13 +: 5]];', 'completion_event_o[lane].trap_value = frontend_value_i[lane*32 +: 32];', 1),
            'lost_original_instruction': ('rtl/backend/control_flow_backend.sv', 'completion_event_o[lane].instruction = fault_instruction_q[completion_id_o[lane*13 +: 5]];', "completion_event_o[lane].instruction = 32'h00000013;", 1),
            'lost_original_pc': ('rtl/backend/control_flow_backend.sv', 'completion_event_o[lane].pc_before = fault_pc_q[completion_id_o[lane*13 +: 5]];', 'completion_event_o[lane].pc_before = producer_event[lane].pc_before;', 1),
            'fault_membership_not_cleared': ('rtl/backend/control_flow_backend.sv', 'fault_q[allocate_id_o[lane*13 +: 5]] <= frontend_fault_i[lane];', 'if (frontend_fault_i[lane]) fault_q[allocate_id_o[lane*13 +: 5]] <= 1;', 1),
            'lost_lane1_metadata': ('rtl/backend/control_flow_backend.sv', 'if (allocate_accept_o[lane]) begin', 'if (allocate_accept_o[lane] && lane == 0) begin', 1),
            'fault_prefix_lost': ('rtl/backend/control_flow_backend.sv', '&& !frontend_fault_i[0]', '', 1),
            'fetch_fault_blocked': ('rtl/core/fetch_execution_core.sv', '(FRONTEND_FAULTS || !fetch_fault_o)', '!fetch_fault_o', 1),
            'fetch_fault_priority_lost': ('rtl/frontend/frontend_fault_decode.sv', 'fetch_fault_i ? fetch_cause_i :', "1'b0 ? fetch_cause_i :", 1),
            'deferred_legal_trapped': ('rtl/frontend/frontend_fault_decode.sv', 'decoded[lane].op inside {OP_ILLEGAL, OP_ECALL, OP_EBREAK}', '!(decoded[lane].op inside {OP_ALU, OP_LUI, OP_AUIPC, OP_BRANCH, OP_JAL, OP_JALR})', 1),
            'younger_held_fault_survives': ('rtl/backend/control_flow_backend.sv', '.flush_i(producer_flush || cancel_alu1)', '.flush_i(producer_flush)', 1),
        },
    ),
    'csr_two_wide': dict(
        top='csr_two_wide', sources=[],
        inputs=['config/csr_two_wide.vlt', 'config/platform.yaml', 'config/commit_event.yaml', 'tools/gen_platform.py', 'tools/gen_commit_event.py'],
        headers=['csr'], schema_checks=['platform-check', 'event-check'], parameters={},
        timeout=900, random_key=None, prefix='CSR TWO WIDE PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('address_sweep') != 4096 or fields.get('cycles', 0) < 80000),
        required=['wfi', 'cancel_wfi', 'reset_wfi', 'trap_over_wfi', 'address_sweep', 'cancel', 'cancel_csr', 'cancel_reset_mret', 'cancel_reset_trap', 'cause_0', 'cause_1', 'cause_11', 'cause_2', 'cause_3', 'cause_4', 'cause_5', 'cause_6', 'cause_7', 'csr', 'csr_read', 'cycle_carry', 'cycle_inhibit', 'cycle_wrap', 'cycle_write_priority', 'dual_retire', 'held', 'illegal', 'instret_carry', 'instret_inhibit', 'instret_wrap', 'instret_write_priority', 'kind_1', 'kind_2', 'kind_3', 'kind_5', 'kind_6', 'kind_7', 'mret', 'no_effective_write', 'prepare', 'read_suppressed', 'reset', 'reset_csr', 'single_retire', 'trap', 'unsupported_instruction'],
        negatives={'bad-count': (['--bad-count'], 'CSR2_RETIRE_COUNT'), 'bad-serialization': (['--bad-serialization'], 'CSR2_SERIALIZE')}, guards={}, extra_runs=[],
        mutation_args=['1'], mismatch='CSR two-wide mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'wfi_illegal': ('rtl/core/csr_two_wide.sv', 'decoded.op inside {OP_MRET, OP_WFI}', 'decoded.op == OP_MRET', 1),
            'wfi_wrong_pc': ('rtl/core/csr_two_wide.sv', "decoded.op == OP_WFI) begin\n      next_pc = pc_i + 32'd4;", 'decoded.op == OP_WFI) begin\n      next_pc = pc_i;', 1),
            'wfi_effect': ('rtl/core/csr_two_wide.sv', 'decoded.op == OP_WFI) begin', "decoded.op == OP_WFI) begin\n      proposal[0] = effect(CSR_MSCRATCH, 32'd1, CSR_MSCRATCH_WRITE_MASK, CSR_MASK_INSTRUCTION);", 1),
            'dual_count_lost': ('rtl/core/csr_two_wide.sv', "64'(increment)", "64'(increment != 0)", 1),
            'trap_retires': ('rtl/core/csr_two_wide.sv', 'assign retired_o = commit_state && !trap_q;', 'assign retired_o = commit_state;', 1),
            'readonly_writable': ('rtl/core/csr_two_wide.sv', '!(write_query && READ_ONLY[query_index])', "1'b1", 1),
            'zero_value_suppresses_write': ('rtl/core/csr_two_wide.sv', 'decoded.zimm != 0;', 'operand != 0;', 1),
            'read_suppression_lost': ('rtl/core/csr_two_wide.sv', '&& !(decoded.funct3[1:0] == 1 && decoded.rd == 0)', '', 1),
            'x0_uses_payload': ('rtl/core/csr_two_wide.sv', "(decoded.rs1 == 0 ? 32'd0 : source_i)", 'source_i', 1),
            'counter_write_priority_lost': ('rtl/core/csr_two_wide.sv', '&& !cycle_write)', ')', 1),
            'instret_write_priority_lost': ('rtl/core/csr_two_wide.sv', '&& !instret_write)', ')', 1),
            'inhibit_lost': ('rtl/core/csr_two_wide.sv', '!csr_q[I_MCOUNTINHIBIT][2]', "1'b1", 1),
            'trap_status_lost': ('rtl/core/csr_two_wide.sv', "{24'd0, csr_q[I_MSTATUS][3], 7'd0}", "32'd0", 1),
            'mret_status_lost': ('rtl/core/csr_two_wide.sv', "{28'd0, csr_q[I_MSTATUS][7], 3'd0}", "32'd0", 1),
            'mepc_alignment_lost': ('rtl/core/csr_two_wide.sv', "pc_i & 32'hfffffffc", 'pc_i', 1),
            'live_counter_response': ('rtl/core/csr_two_wide.sv', "assign value_o = response_valid_o ? value_q : 32'd0;", "assign value_o = response_valid_o ? old_value : 32'd0;", 1),
            'cancel_still_commits': ('rtl/core/csr_two_wide.sv', 'assign response_valid_o = !rst_i && !cancel_i && pending_q;', 'assign response_valid_o = !rst_i && pending_q;', 1),
            'updates_while_held': ('rtl/core/csr_two_wide.sv', 'wire commit_state = accept_o && legal_q;', 'wire commit_state = response_valid_o && legal_q;', 1),
            'trap_target_wrong': ('rtl/core/csr_two_wide.sv', 'next_pc = mtvec_o;', 'next_pc = mepc_o;', 1),
            'trap_value_lost': ('rtl/core/csr_two_wide.sv', 'effect(CSR_MTVAL, trap_value_i,', "effect(CSR_MTVAL, 32'd0,", 1),
            'effect_mask_wrong': ('rtl/core/csr_two_wide.sv', 'result.read_mask = WRITE_MASK[i] | FIXED_MASK[i];', 'result.read_mask = WRITE_MASK[i];', 1),
        },
    ),
    'head_trap_core': dict(
        top='fetch_execution_core', sources=[],
        inputs=['verif/unit/fetch_execution_reference.hpp', 'config/fetch_execution_core.json', 'config/fetch_execution_core.vlt', 'config/platform.yaml', 'config/memory_protocol.yaml', 'config/commit_event.yaml', 'config/csr_two_wide.json', 'config/control_flow_backend.json', 'config/fetch_two_wide.json', 'config/issue_backend.json', 'config/backend_two_wide.json', 'config/issue_queue.json', 'config/rob_two_wide.json', 'config/prf_contract.json', 'tools/gen_platform.py', 'tools/gen_memory_protocol.py', 'tools/gen_commit_event.py'],
        headers=['event', 'memory', 'csr'], schema_checks=['platform-check', 'memory-check', 'event-check'], parameters={'FRONTEND_FAULTS': 1, 'TRAP_SERVICE': 1},
        timeout=900, random_key=None, prefix='HEAD TRAP CORE PASS ',
        geometry=lambda config: not (config['parameters'] != {'FRONTEND_FAULTS': 1, 'TRAP_SERVICE': 1}),
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('traps', 0) < 470 or fields.get('retired', 0) < 6000 or (fields.get('cycles', 0) < 15000)),
        required=['ecall_lane0', 'ecall_lane1', 'ebreak_lane0', 'ebreak_lane1', 'backend_fault', 'bus_offset_0', 'bus_offset_1', 'bus_offset_2', 'bus_offset_3', 'bus_offset_4', 'bus_offset_5', 'bus_offset_6', 'bus_offset_7', 'completion_stall', 'drain', 'dual_dispatch', 'dual_retire', 'fatal_prepared', 'fault_offset_0', 'fault_offset_1', 'fault_offset_2', 'fault_offset_3', 'fault_offset_4', 'fault_offset_5', 'fault_offset_6', 'fault_offset_7', 'fetch_fault_dispatch', 'flush_prepared', 'frontend_alignment', 'frontend_bus_fault', 'frontend_pma', 'handler_fault', 'illegal_lane0', 'illegal_lane1', 'local_fault', 'normal_program', 'op_0', 'op_1', 'op_10', 'op_11', 'op_12', 'op_13', 'op_14', 'op_15', 'op_16', 'op_17', 'op_18', 'op_19', 'op_2', 'op_20', 'op_21', 'op_22', 'op_23', 'op_24', 'op_25', 'op_26', 'op_27', 'op_28', 'op_3', 'op_4', 'op_5', 'op_6', 'op_7', 'op_8', 'op_9', 'ready_before_fault', 'reset_prepared', 'retire_stall', 'slot_reuse', 'target_fault_21', 'target_fault_27', 'target_fault_28', 'trap_accept', 'trap_offered_fetch', 'trap_over_younger_branch', 'trap_pending_fetch', 'trap_stall', 'wrong_path_0', 'wrong_path_1', 'wrong_path_2', 'wrong_path_3'],
        negatives={}, guards={}, extra_runs=[],
        mutation_args=['1'], mismatch='fetch execution core mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'lost_rob_accept': ('rtl/backend/control_flow_backend.sv', '.trap_ready_i(backend_trap_ready)', ".trap_ready_i(1'b0)", 1),
            'lost_producer_clear': ('rtl/backend/control_flow_backend.sv', 'wire producer_flush = flush_i || trap_accept_o;', 'wire producer_flush = flush_i;', 1),
            'lost_rename_restore': ('rtl/backend/backend_two_wide.sv', 'wire recover = flush_i || trap_accept_o;', 'wire recover = flush_i;', 1),
            'lost_order_advance': ('rtl/backend/rob_two_wide.sv', " + 64'(trap_accept_o)", '', 1),
            'lost_csr_accept': ('rtl/core/head_system_controller.sv', '.response_ready_i(accepted_serial || accepted_illegal || accepted_trap)', '.response_ready_i(accepted_serial || accepted_illegal)', 1),
            'early_csr_accept': ('rtl/core/head_system_controller.sv', '.response_ready_i(accepted_serial || accepted_illegal || accepted_trap)', '.response_ready_i(accepted_serial || accepted_illegal || trap_valid_o)', 1),
            'lost_trap_redirect': ('rtl/core/fetch_execution_core.sv', '(flush_i || system_redirect || branch_redirect)', '(flush_i || branch_redirect)', 1),
            'wrong_handler_target': ('rtl/core/fetch_execution_core.sv', 'system_redirect ? system_pc', "system_redirect ? 32'd0", 1),
            'younger_branch_wins': ('rtl/backend/control_flow_backend.sv', '.resolve_grant_i(resolve_grant_i && !(SYSTEM_SERVICE && (system_busy_o || fault_pending_o)))', '.resolve_grant_i(resolve_grant_i)', 1),
            'flush_keeps_proposal': ('rtl/backend/control_flow_backend.sv', '.cancel_i(flush_i || cancel_system_i)', '.cancel_i(cancel_system_i && !flush_i)', 1),
            'fatal_keeps_proposal': ('rtl/core/fetch_execution_core.sv', '.cancel_system_i(flush_i || !running)', '.cancel_system_i(flush_i)', 1),
            'trap_marked_retired': ('rtl/core/head_system_controller.sv', 'trap_event_o = saved_q;', 'trap_event_o = saved_q; trap_event_o.retired = 1;', 1),
            'lost_csr_effects': ('rtl/core/head_system_controller.sv', 'trap_event_o.csr_effects = effects;', "trap_event_o.csr_effects = '0;", 1),
            'raw_next_pc': ('rtl/core/head_system_controller.sv', 'trap_event_o.pc_after = next_pc;', 'trap_event_o.pc_after = saved_q.pc_after;', 1),
            'lost_trap_value': ('rtl/core/csr_two_wide.sv', 'effect(CSR_MTVAL, trap_value_i,', "effect(CSR_MTVAL, 32'd0,", 1),
            'lost_mepc_write': ('rtl/core/csr_two_wide.sv', 'CSR_MEPC_WRITE_MASK, CSR_MASK_TRAP_ENTRY', "32'd0, CSR_MASK_TRAP_ENTRY", 1),
        },
    ),
    'serial_retirement': dict(
        top='backend_two_wide', sources=[],
        inputs=['verif/unit/backend_reference.hpp', 'config/backend_two_wide.json', 'config/rob_two_wide.json', 'config/rename_recovery.json', 'config/prf_contract.json', 'config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=['event'], schema_checks=['event-check'], parameters={},
        timeout=900, random_key=None, prefix='SERIAL RETIREMENT PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('serial_accept', 0) < 1800 or fields.get('cycles', 0) < 10000),
        required=['drain', 'flush_offer', 'full_window', 'older_branch_kill', 'older_writer', 'prf_bypass', 'random_cancel', 'random_serial', 'rd_0', 'rd_1', 'rd_10', 'rd_11', 'rd_12', 'rd_13', 'rd_14', 'rd_15', 'rd_16', 'rd_17', 'rd_18', 'rd_19', 'rd_2', 'rd_20', 'rd_21', 'rd_22', 'rd_23', 'rd_24', 'rd_25', 'rd_26', 'rd_27', 'rd_28', 'rd_29', 'rd_3', 'rd_30', 'rd_31', 'rd_4', 'rd_5', 'rd_6', 'rd_7', 'rd_8', 'rd_9', 'recovery_priority', 'reject_0', 'reject_1', 'reject_2', 'reject_3', 'reject_4', 'reject_5', 'reject_6', 'reject_7', 'reject_8', 'reject_9', 'repeated_offer', 'reset_offer', 'serial_accept', 'serial_blocks_allocation', 'serial_blocks_completion', 'serial_no_destination', 'serial_rejected', 'serial_stall', 'trap_priority'],
        negatives={}, guards={}, extra_runs=[],
        mutation_args=['1'], mismatch='backend two wide mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'early_write': ('rtl/backend/backend_two_wide.sv', 'lane == 0 && retire_ready_i[0] && serial_event_i.rd_write_mask != 0', 'lane == 0 && serial_event_i.rd_write_mask != 0', 1),
            'no_serial_write': ('rtl/backend/backend_two_wide.sv', 'lane == 0 && retire_ready_i[0] && serial_event_i.rd_write_mask != 0', "1'b0", 1),
            'wrong_payload': ('rtl/backend/backend_two_wide.sv', "{32'd0, serial_event_i.rd_value}", "64'd0", 1),
            'lost_commit': ('rtl/backend/backend_two_wide.sv', '.commit_i(commit_request)', ".commit_i(serial_selected ? 2'b00 : commit_request)", 1),
            'stale_identity': ('rtl/backend/rob_two_wide.sv', 'serial_id_i == head_id_o', 'serial_id_i[4:0] == head_id_o[4:0]', 1),
            'not_solo': ('rtl/backend/rob_two_wide.sv', '&& solo_q[head_q] && !cfi_q[head_q]', '&& !cfi_q[head_q]', 1),
            'cfi_allowed': ('rtl/backend/rob_two_wide.sv', '&& !cfi_q[head_q] && serial_id_i', '&& serial_id_i', 1),
            'bad_pc_allowed': ('rtl/backend/rob_two_wide.sv', 'serial_event_i.pc_before == pc_q[head_q]', "1'b1", 1),
            'bad_rd_allowed': ('rtl/backend/rob_two_wide.sv', 'serial_event_i.rd_addr == rd_q[head_q]', "1'b1", 1),
            'bad_mask_allowed': ('rtl/backend/rob_two_wide.sv', "serial_event_i.rd_write_mask == (rd_q[head_q] == 0 ? 32'd0 : 32'hffffffff)", "1'b1", 1),
            'ordinary_completion_leak': ('rtl/backend/rob_two_wide.sv', '!clear_window && !serial_selected && valid_q', '!clear_window && valid_q', 1),
            'allocation_leak': ('rtl/backend/rob_two_wide.sv', '&& !drained_i && !serial_selected) begin', '&& !drained_i) begin', 1),
            'wrong_event': ('rtl/backend/rob_two_wide.sv', 'serial_selected ? serial_event_i : event_q[head_q]', 'event_q[head_q]', 1),
            'ignored_sink': ('rtl/backend/backend_two_wide.sv', 'retire_valid_o[0] && retire_ready_i[0]', 'retire_valid_o[0]', 1),
        },
    ),
    'head_system_backend': dict(
        top='head_system_backend', sources=[],
        inputs=['verif/unit/csr_reference.hpp', 'config/head_system_backend.vlt', 'config/platform.yaml', 'tools/gen_platform.py', 'config/csr_two_wide.json', 'config/backend_two_wide.json', 'config/rob_two_wide.json', 'config/rename_recovery.json', 'config/prf_contract.json', 'config/commit_event.yaml', 'tools/gen_commit_event.py'],
        headers=['event', 'csr'], schema_checks=['platform-check', 'event-check'], parameters={},
        timeout=900, random_key=None, prefix='HEAD SYSTEM PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: not (fields.get('seed') != seed or fields.get('address_sweep') != 4096 or fields.get('cycles', 0) < 10000),
        required=['wfi', 'address_sweep', 'branch_kill', 'cancel_1', 'cancel_2', 'cancel_pending', 'drain', 'dual_retire', 'held_illegal', 'held_input_change', 'held_serial', 'held_trap', 'illegal', 'kind_1', 'kind_2', 'kind_3', 'kind_5', 'kind_6', 'kind_7', 'mret', 'nonhead_descriptor', 'older_dependency', 'raw_trap_0', 'raw_trap_1', 'raw_trap_2', 'serial', 'serial_bypass', 'stale_descriptor', 'trap'],
        negatives={}, guards={}, extra_runs=[],
        mutation_args=['1'], mismatch='head system mismatch', mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL', '-Wno-UNUSEDPARAM'],
        mutations={
            'early_state': ('rtl/core/head_system_controller.sv', '.response_ready_i(accepted_serial || accepted_illegal || accepted_trap)', '.response_ready_i(serial_offer_o || accepted_illegal || accepted_trap)', 1),
            'lost_serial_accept': ('rtl/core/head_system_controller.sv', '.response_ready_i(accepted_serial || accepted_illegal || accepted_trap)', '.response_ready_i(accepted_illegal || accepted_trap)', 1),
            'wrong_result': ('rtl/core/head_system_controller.sv', "saved_q.rd_addr == 0 ? 32'd0 : value", "32'd0", 1),
            'lost_effects': ('rtl/core/head_system_controller.sv', 'serial_event_o.csr_effects = effects;', "serial_event_o.csr_effects = '0;", 1),
            'stale_descriptor': ('rtl/core/head_system_controller.sv', 'system_id_i == head_id_i', 'system_id_i[4:0] == head_id_i[4:0]', 1),
            'early_redirect': ('rtl/core/head_system_controller.sv', '(accepted_serial && mret_q)', '(serial_offer_o && mret_q)', 1),
            'wrong_redirect': ('rtl/core/head_system_controller.sv', "redirect_o ? next_pc : 32'd0", "redirect_o ? saved_q.pc_before : 32'd0", 1),
            'lost_source': ('rtl/core/head_system_controller.sv', '.source_i,', ".source_i(32'd0),", 1),
            'lost_dual_count': ('rtl/core/head_system_controller.sv', "2'($countones(retire_accept_i & ~{1'b0, serial_accept_i}))", "2'(|(retire_accept_i & ~{1'b0, serial_accept_i}))", 1),
            'wrong_illegal_value': ('rtl/core/head_system_controller.sv', 'illegal_event_o.trap_value = saved_q.instruction;', 'illegal_event_o.trap_value = 0;', 1),
            'illegal_retires': ('rtl/core/head_system_controller.sv', '&& !trap_q && legal;', '&& !trap_q;', 1),
            'cancel_keeps_response': ('rtl/core/csr_two_wide.sv', 'assign response_valid_o = !rst_i && !cancel_i && pending_q;', 'assign response_valid_o = !rst_i && pending_q;', 1),
            'trap_retires': ('rtl/core/csr_two_wide.sv', 'assign retired_o = commit_state && !trap_q;', 'assign retired_o = commit_state;', 1),
            'mret_status': ('rtl/core/csr_two_wide.sv', "{28'd0, csr_q[I_MSTATUS][7], 3'd0}", "32'd0", 1),
            'lost_trap_accept': ('verif/unit/head_system_backend.sv', '.trap_ready_i(trap_accept_o)', ".trap_ready_i(1'b0)", 1),
        },
    ),
    'head_system_dispatch': dict(
        top='head_system_dispatch', sources=[], inputs=[],
        headers=[], schema_checks=[], parameters={}, timeout=180,
        random_key='random_cycles_per_seed', prefix='HEAD SYSTEM DISPATCH PASS ',
        geometry=lambda config: True,
        validate=lambda config, fields, seed: fields.get('seed') == seed and fields.get('cycles') == config['directed_cycles'] + config['random_cycles_per_seed'],
        required=['wfi', 'dual_ordinary', 'lane1_deferred', 'system_tail_cut', 'cfi_cut', 'allocation_stall', 'drain_idle', 'held', 'younger_blocked', 'changed_inputs', 'no_head', 'stale_generation', 'wrong_pc', 'older_head', 'recover_kill', 'recover_preserve', 'wrap_recovery', 'reset_live', 'flush_live', 'retired', 'release_bubble', 'captured', 'register_source', 'zero_source', 'mret', 'immediate', 'register_csr', 'generation_capture', 'recovery_blocked', 'head_recovery_blocked'],
        negatives={'wfi-source': (['negative', 'wfi-source'], 'SYSTEM_DISPATCH_SOURCE'), 'prefix': (['negative', 'prefix'], 'SYSTEM_DISPATCH_PREFIX'), 'allocation': (['negative', 'allocation'], 'SYSTEM_DISPATCH_ALLOCATION'), 'operation': (['negative', 'operation'], 'SYSTEM_DISPATCH_OPERATION'), 'source': (['negative', 'source'], 'SYSTEM_DISPATCH_SOURCE'), 'retire': (['negative', 'retire'], 'SYSTEM_DISPATCH_RETIRE'), 'drain': (['negative', 'drain'], 'SYSTEM_DISPATCH_DRAIN'), 'recovery': (['negative', 'recovery'], 'SYSTEM_DISPATCH_RECOVERY')}, guards={}, extra_runs=[],
        mutation_args=['1', '0'], mismatch='head system dispatch mismatch',
        mutation_flags=['-DSYNTHESIS', '-Wno-UNUSEDSIGNAL'],
        mutations={
            'younger_dispatch': ('rtl/core/head_system_dispatch.sv', '!valid_q && !blocked', '!blocked', 1),
            'lane1_system': ('rtl/core/head_system_dispatch.sv', '&& !cfi0_i && !system_i[0] && !system_i[1]', '&& !cfi0_i && !system_i[0]', 1),
            'system_tail': ('rtl/core/head_system_dispatch.sv', '&& !cfi0_i && !system_i[0] && !system_i[1]', '&& !cfi0_i && !system_i[1]', 1),
            'cfi_tail': ('rtl/core/head_system_dispatch.sv', '&& !cfi0_i && !system_i[0] && !system_i[1]', '&& !system_i[0] && !system_i[1]', 1),
            'iq_system_leak': ('rtl/core/head_system_dispatch.sv', 'allocate_accept_i & ~system_i', 'allocate_accept_i', 1),
            'lost_solo': ('rtl/core/head_system_dispatch.sv', 'dispatch_valid_o & system_i', "2'b00", 1),
            'wrong_source': ('rtl/core/head_system_dispatch.sv', 'source_q <= source1_i[5:0];', "source_q <= source1_i[5:0] ^ 6'd1;", 1),
            'wrong_identity': ('rtl/core/head_system_dispatch.sv', 'id_q <= allocate_id_i[12:0];', "id_q <= allocate_id_i[12:0] ^ 13'd32;", 1),
            'wrong_instruction': ('rtl/core/head_system_dispatch.sv', 'instruction_q <= instruction_i[31:0];', "instruction_q <= instruction_i[31:0] ^ 32'd128;", 1),
            'wrong_pc': ('rtl/core/head_system_dispatch.sv', 'pc_q <= pc_i[31:0];', "pc_q <= pc_i[31:0] ^ 32'd4;", 1),
            'slot_only_head': ('rtl/core/head_system_dispatch.sv', 'head_id_i == id_q', 'head_id_i[4:0] == id_q[4:0]', 1),
            'ignore_pc': ('rtl/core/head_system_dispatch.sv', '&& head_pc_i == pc_q', '', 1),
            'early_release': ('rtl/core/head_system_dispatch.sv', 'else if (release_owner) valid_q <= 0;', 'else if (system_valid_o) valid_q <= 0;', 1),
            'lost_release': ('rtl/core/head_system_dispatch.sv', 'else if (release_owner) valid_q <= 0;', 'else if (release_owner) valid_q <= valid_q;', 1),
            'wrong_recovery_age': ('rtl/core/head_system_dispatch.sv', "5'(id_q[4:0] - head_id_i[4:0]) > 5'(recover_slot_i - head_id_i[4:0])", 'id_q[4:0] > recover_slot_i', 1),
            'kill_older': ('rtl/core/head_system_dispatch.sv', 'recover_i && younger', 'recover_i && !younger', 1),
            'flush_retains': ('rtl/core/head_system_dispatch.sv', 'if (rst_i || flush_i || kill) valid_q <= 0;', 'if (rst_i || kill) valid_q <= 0;', 1),
            'capture_on_offer': ('rtl/core/head_system_dispatch.sv', 'allocate_accept_i[0] && system_i[0]', 'dispatch_valid_o[0] && system_i[0]', 1),
            'live_source': ('rtl/core/head_system_dispatch.sv', "valid_q ? source_q : 6'd0", "valid_q ? source1_i[5:0] : 6'd0", 1),
            'recover_offer': ('rtl/core/head_system_dispatch.sv', 'wire blocked = rst_i || flush_i || drained_i || recover_i;', 'wire blocked = rst_i || flush_i || drained_i;', 1),
        },
    ),
    'system_core': dict(
        top='fetch_execution_core', sources=[],
        inputs=['config/platform.yaml','config/memory_protocol.yaml','config/commit_event.yaml','config/head_system_dispatch.json','config/head_system_backend.json','config/control_flow_backend.json','config/issue_backend.json','config/backend_two_wide.json','config/csr_two_wide.json','tools/gen_platform.py','tools/gen_memory_protocol.py','tools/gen_commit_event.py'],
        headers=['event','memory','csr'], schema_checks=['platform-check','event-check','memory-check'],
        parameters={'FRONTEND_FAULTS':1,'TRAP_SERVICE':1}, timeout=900,
        random_key=None, prefix='SYSTEM CORE PASS ', geometry=lambda config: config['parameters']=={'FRONTEND_FAULTS':1,'TRAP_SERVICE':1},
        validate=lambda config, fields, seed: fields.get('seed')==seed and fields.get('retired',0)>3000 and fields.get('traps',0)>=3,
        required=['wfi_retired', 'wfi_seen_lane0', 'wfi_seen_lane1', 'wfi_older_work', 'wfi_counted', 'wfi_inhibited', 'wrong_path_wfi', 'wfi_hold_0', 'wfi_hold_2', 'reset_wfi', 'flush_wfi', 'fatal_wfi', 'wfi_offset_0', 'wfi_offset_1', 'wfi_offset_2', 'wfi_offset_3', 'wfi_offset_4', 'wfi_offset_5', 'wfi_offset_6', 'wfi_offset_7', 'ecall_lane0', 'ecall_lane1', 'ebreak_lane0', 'ebreak_lane1', 'trap_return_3', 'trap_return_4', 'environment_offset_0', 'environment_offset_1', 'environment_offset_2', 'environment_offset_3', 'environment_offset_4', 'environment_offset_5', 'environment_offset_6', 'environment_offset_7', 'csr_retired', 'mret_retired', 'system_held', 'wrong_path_system', 'flush_system', 'reset_system', 'fatal_system', 'mret_pending_fetch', 'mret_offered_fetch', 'random_program', 'dual_dispatch', 'dual_retire', 'trap_accept', 'system_prepare', 'hold_mask_0', 'hold_mask_2', 'offset_0', 'offset_1', 'offset_2', 'offset_3', 'offset_4', 'offset_5', 'offset_6', 'offset_7', 'kind_1', 'kind_2', 'kind_3', 'kind_5', 'kind_6', 'kind_7', 'trap_return_0', 'trap_return_1', 'trap_return_2'],
        negatives={}, guards={}, extra_runs=[], mutation_args=['1'], mismatch='fetch execution core mismatch',
        mutation_flags=['-DSYNTHESIS','-Wno-UNUSEDSIGNAL','-Wno-UNUSEDPARAM'], mutations={
            'wfi_unsupported': ('rtl/backend/control_flow_backend.sv', '{OP_CSR, OP_MRET, OP_WFI}', '{OP_CSR, OP_MRET}', 1),
            'wfi_redirect': ('rtl/core/head_system_controller.sv', 'decoded.op == OP_MRET;', 'decoded.op inside {OP_MRET, OP_WFI};', 1),
            'wfi_not_counted': ('rtl/core/csr_two_wide.sv', "wire [1:0] increment = retired_o ? 2'd1 : retire_count_i;", "wire [1:0] increment = retired_o && effects_q[0].valid ? 2'd1 : retire_count_i;", 1),
            'younger_dispatch': ('rtl/core/head_system_dispatch.sv', '!valid_q && !blocked', '!blocked', 1),
            'lane1_system_not_deferred': ('rtl/core/head_system_dispatch.sv', '&& !cfi0_i && !system_i[0] && !system_i[1]', '&& !cfi0_i && !system_i[0]', 1),
            'system_enters_iq': ('rtl/backend/issue_backend.sv', '.dispatch_i(allocate_accept_o & ~queue_skip_i)', '.dispatch_i(allocate_accept_o)', 1),
            'lost_head_read': ('rtl/backend/issue_backend.sv', "head_read_i ? {18'd0, head_source_i} : issue_source_o", 'issue_source_o', 1),
            'wrong_captured_source': ('rtl/core/head_system_dispatch.sv', 'source_q <= source1_i[5:0];', "source_q <= source1_i[5:0] ^ 6'd1;", 1),
            'wrong_descriptor_identity': ('rtl/core/head_system_dispatch.sv', 'id_q <= allocate_id_i[12:0];', "id_q <= allocate_id_i[12:0] ^ 13'd32;", 1),
            'lost_serial_path': ('rtl/backend/issue_backend.sv', '.serial_offer_i, .serial_id_i,', ".serial_offer_i(1'b0), .serial_id_i,", 1),
            'early_csr_state': ('rtl/core/head_system_controller.sv', '.response_ready_i(accepted_serial || accepted_illegal || accepted_trap)', '.response_ready_i(serial_offer_o || accepted_illegal || accepted_trap)', 1),
            'lost_illegal_completion': ('rtl/backend/control_flow_backend.sv', "illegal_offer ? {1'b0, completion_enable_i[0]}", "illegal_offer ? 2'b00", 1),
            'wrong_illegal_value': ('rtl/core/head_system_controller.sv', 'illegal_event_o.trap_value = saved_q.instruction;', "illegal_event_o.trap_value = 32'd0;", 1),
            'lost_mret_redirect': ('rtl/core/head_system_controller.sv', 'accepted_trap || (accepted_serial && mret_q)', 'accepted_trap', 1),
            'early_mret_redirect': ('rtl/core/head_system_controller.sv', 'accepted_trap || (accepted_serial && mret_q)', 'accepted_trap || (serial_offer_o && mret_q)', 1),
            'wrong_mret_target': ('rtl/core/head_system_controller.sv', "redirect_o ? next_pc : 32'd0", "redirect_o ? saved_q.pc_before : 32'd0", 1),
            'wrong_path_csr_survives': ('rtl/core/head_system_dispatch.sv', 'recover_i && younger', "1'b0 && younger", 1),
            'lost_dual_retire_count': ('rtl/core/head_system_controller.sv', "2'($countones(retire_accept_i & ~{1'b0, serial_accept_i}))", "2'(|(retire_accept_i & ~{1'b0, serial_accept_i}))", 1),
            'cancel_keeps_state': ('rtl/core/csr_two_wide.sv', '!rst_i && !cancel_i && pending_q', '!rst_i && pending_q', 1),
            'wrong_mret_status': ('rtl/core/csr_two_wide.sv', "{28'd0, csr_q[I_MSTATUS][7], 3'd0}", "32'd0", 1),
            'serial_no_prf_write': ('rtl/backend/backend_two_wide.sv', 'lane == 0 && retire_ready_i[0] && serial_event_i.rd_write_mask != 0', "1'b0", 1),
        },
    ),
    'load_store_prepare': dict(
        top='load_store_prepare', sources=[],
        inputs=['config/platform.yaml', 'tools/gen_platform.py'],
        headers=['pma'], schema_checks=['platform-check'], parameters={}, timeout=300,
        random_key='random_cycles_per_seed', prefix='LOAD STORE PREPARE PASS ',
        geometry=lambda config: config['schema']==1,
        validate=lambda config, fields, seed: fields.get('seed')==seed and fields.get('cycles',0)>config['random_cycles_per_seed']+15000,
        required=['taken','held','turnover','reset_live','flush_live','generation','x0_base','x0_store','x0_load',
                  'ram','mmio','head_only','speculative_eligible','load_0','load_1','load_2','load_4','load_5',
                  'store_0','store_1','store_2','cause_4','cause_5','cause_6','cause_7',
                  *['lane_'+str(n) for n in range(4)], *['slot_'+str(n) for n in range(32)]],
        negatives={name: (['negative',name], marker) for name,marker in [
            ('capacity','LS_PREP_CAPACITY'),('take','LS_PREP_TAKE'),('pc','LS_PREP_PC'),
            ('operation','LS_PREP_OPERATION'),('reserved-load','LS_PREP_OPERATION'),('reserved-store','LS_PREP_OPERATION')]},
        guards={}, extra_runs=[], mutation_args=['1','0'], mismatch='load store prepare mismatch',
        mutation_flags=['-DSYNTHESIS','-Wno-UNUSEDSIGNAL','-Wno-UNUSEDPARAM'],
        mutations={
            'address_subtract': ('rtl/execute/execute_single.sv', 'source1_i + decoded_i.immediate;', 'source1_i - decoded_i.immediate;', 1),
            'x0_base_payload': ('rtl/execute/load_store_prepare.sv', "decoded.rs1 == 0 ? 32'd0 : source1_i", 'source1_i', 1),
            'x0_store_payload': ('rtl/execute/load_store_prepare.sv', "decoded.rs2 == 0 ? 32'd0 : source2_i", 'source2_i', 1),
            'unsigned_lost': ('rtl/execute/load_store_prepare.sv', 'decoded.op == OP_LOAD && decoded.funct3[2]', "1'b0", 1),
            'size_lost': ('rtl/execute/load_store_prepare.sv', 'built.size = decoded.funct3[1:0];', "built.size = 2'd0;", 1),
            'byte_lane_lost': ('rtl/execute/load_store_prepare.sv', "4'b0001 << address[1:0]", "4'b0001", 1),
            'half_mask': ('rtl/execute/load_store_prepare.sv', "4'b0011 << address[1:0]", "4'b0001 << address[1:0]", 1),
            'store_shift_lost': ('rtl/execute/load_store_prepare.sv', "(data << {address[1:0], 3'b000})", 'data', 1),
            'store_mask_lost': ('rtl/execute/load_store_prepare.sv', '& byte_mask(built.mask)', '', 1),
            'access_fault_lost': ('rtl/execute/execute_single.sv', 'else if (!accessible(address_o, decoded_i.op == OP_STORE))', "else if (1'b0 && !accessible(address_o, decoded_i.op == OP_STORE))", 1),
            'half_alignment_lost': ('rtl/execute/execute_single.sv', 'decoded_i.funct3[1:0] == 1 && address_o[0]', "decoded_i.funct3[1:0] == 1 && 1'b0", 1),
            'store_cause': ('rtl/execute/execute_single.sv', 'CAUSE_STORE_ACCESS_FAULT : CAUSE_LOAD_ACCESS_FAULT', 'CAUSE_LOAD_ACCESS_FAULT : CAUSE_LOAD_ACCESS_FAULT', 1),
            'fault_value': ('rtl/execute/execute_single.sv', 'if (trap_o) trap_value_o = address_o;', "if (trap_o) trap_value_o = 32'd0;", 1),
            'mmio_speculates': ('rtl/execute/load_store_prepare.sv', 'fault || built.store || !cached(address) || !idempotent', 'fault || built.store', 1),
            'store_speculates': ('rtl/execute/load_store_prepare.sv', 'fault || built.store || !cached(address) || !idempotent', 'fault || !cached(address) || !idempotent', 1),
            'uncached_lost': ('rtl/execute/load_store_prepare.sv', 'built.uncached = !cached(address);', "built.uncached = 1'b0;", 1),
            'fault_mask_leak': ('rtl/execute/load_store_prepare.sv', 'if (!fault) begin', "if (1'b1) begin", 1),
            'identity_generation_lost': ('rtl/execute/load_store_prepare.sv', 'built.id = id_i;', "built.id = {8'd0, id_i[4:0]};", 1),
            'held_payload_changes': ('rtl/execute/load_store_prepare.sv', 'if (launch_i) begin', 'if (launch_i || pending_q) begin', 1),
            'flush_retains': ('rtl/execute/load_store_prepare.sv', 'if (rst_i || flush_i) pending_q <= 0;', 'if (rst_i) pending_q <= 0;', 1),
            'turnover_lost': ('rtl/execute/load_store_prepare.sv', 'if (launch_i) begin', 'if (launch_i && !take_i) begin', 1),
            'invalid_payload': ('rtl/execute/load_store_prepare.sv', "valid_o ? saved_q : '0", 'saved_q', 1),
        },
    ),

}
